# Internal configs
set(CMAKE_UNIX_GENERATOR_PLATFORM x64)
set(JUG_BUILD_PLATFORM_NAME x86_64)

# CMake configs
#set(CMAKE_SYSTEM_NAME ?)
#set(CMAKE_SYSTEM_PROCESSOR ?)
#set(CMAKE_LIBRARY_PATH "?")
#set(CMAKE_INCLUDE_PATH "?")
#set(CMAKE_FIND_ROOT_PATH "?")
#set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
#set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# C/C++ compiler configs
#set(CMAKE_C_COMPILER ?)
#set(CMAKE_CXX_COMPILER ?)
#set(CMAKE_CROSSCOMPILING_EMULATOR ?)

# C/C++ flags & linker flags
#set(CMAKE_C_FLAGS "?" CACHE STRING "" FORCE)
#set(CMAKE_CXX_FLAGS "?" CACHE STRING "" FORCE)
#set(CMAKE_EXE_LINKER_FLAGS "?" CACHE STRING "" FORCE)
#set(CMAKE_SHARED_LINKER_FLAGS "?" CACHE STRING "" FORCE)
